# Generated by Django 3.1.1 on 2020-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gold', models.IntegerField(default=1000)),
                ('atk', models.IntegerField()),
            ],
        ),
    ]
